### ISSUE TITLE
Honolulu Answers link in Readme gives a 404

### ISSUE THREAD

**Issue by maxcodes** [codeforamerica/honolulu_answers#61]
It's the first link of the Readme. The link is http://answers.honolulu.gov/, which redirects to http://www.honolulu.gov/error3.html

**Comment by mapmeld** [comment]
yeah. so it goes :cry:

**Comment by maxhm10** [comment]
what happened?

**Comment by StraubCreative** [comment]
Not sure...been combing the feeds and nothing's out there. The app made it
for almost 2 years though - maybe not enough people were using it?

Oakland is still up btw: http://answers.oaklandnet.com/

On Mon, Jan 5, 2015 at 10:16 AM, Max Holzheu <notifications@github.com>
wrote:

> what happened?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/honolulu_answers/issues/61#issuecomment-68750254>
> .
>



-- 

*Straub Creative Company*

*Zachary Straub *| Founder / Owner

*Let’s Build Better Things Together*

a: 100 Ellwood Avenue, Buffalo, NY 14223

p: (716) 301-0973 | e: zac@straubcreative.com

w: http://straubcreative.nationbuilder.com

<https://www.facebook.com/straubcreativecompany>
<https://twitter.com/straubcreative>
<https://plus.google.com/+StraubCreativeCompanyBuffalo/>
<https://www.linkedin.com/profile/view?id=118012357&trk=nav_responsive_tab_profile>
   <http://www.pinterest.com/straubcreative/>
<http://www.yelp.com/biz/straub-creative-company-buffalo>
<https://foursquare.com/v/straub-creative-company/543867d6498e0160f9de7d99>

**Comment by ssfinney** [comment]
It would be great to know why the usage went down (if that was the problem)

**Comment by StraubCreative** [comment]
Agreed - all of the site metrics were highly favorable according to Alexa:
http://www.alexa.com/siteinfo/answers.honolulu.gov

Tons of strong backlinks and site authority. It was on page 1 for the word
"honolulu" - Google loved this thing and search engines were sending tons
of traffic their way. A few free traffic tools suggested that it was
getting 4-5k visitors per month while it was online, capping at around 250k
total visitors since it's launch in July 2012 (I think that's the correct
date).

Maybe we poke at CoA on social media to get an expo here? The exit strategy
of their app, favorable or otherwise, is important to know!

On Mon, Jan 5, 2015 at 10:38 AM, Stephen Finney <notifications@github.com>
wrote:

> It would be great to know why the usage went down (if that was the problem)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/honolulu_answers/issues/61#issuecomment-68753638>
> .
>



-- 

*Straub Creative Company*

*Zachary Straub *| Founder / Owner

*Let’s Build Better Things Together*

a: 100 Ellwood Avenue, Buffalo, NY 14223

p: (716) 301-0973 | e: zac@straubcreative.com

w: http://straubcreative.nationbuilder.com

<https://www.facebook.com/straubcreativecompany>
<https://twitter.com/straubcreative>
<https://plus.google.com/+StraubCreativeCompanyBuffalo/>
<https://www.linkedin.com/profile/view?id=118012357&trk=nav_responsive_tab_profile>
   <http://www.pinterest.com/straubcreative/>
<http://www.yelp.com/biz/straub-creative-company-buffalo>
<https://foursquare.com/v/straub-creative-company/543867d6498e0160f9de7d99>

**Comment by mapmeld** [comment]
To elaborate: I worked on the project and there is no deep story. As far as I know, a few months after we finished a contract in 2014, Honolulu turned it off. I first heard saw the 404 page in September.

**Comment by snajmi** [comment]
There was a change in the City of Honolulu's govt administration right after our Fellowship year ended. The new administration let Honolulu Answers run for nearly 2 years before turning it off. We have the data backup, so we could host it as our own Heroku instance (do I hear any volunteers?). 

The great news is that Honolulu Answers was replicated by many cities/countries:
[Anchorage Answers](http://www.anchorageanswers.com/)
[Oakland Answers](http://answers.oaklandnet.com/) 
[Western Michigan](http://wmgreenguide.com)
[Muenster FAQ](http://faq.codeformuenster.org/)
[Peru (Lambayeque region)](http://consulta.progob.org.pe/)
[Rehnuma (Pakistan)](http://www.kprehnuma.info/)
[18F (US Federal Govt)](https://github.com/18F/answers)
[Rockford Answers](http://www.codeforrockford.com/news/rockford-answers/)
[Sacramento Answers](https://github.com/code4sac/sacramento_answers)

And has 69 other forks on GitHub. Plus, it inspired a few others that weren't actual GitHub redeployments (including [Verificalo](http://verificalo.mx/respuestas)). Let me know if you know of others.

**Comment by JCody** [comment]
Currently working on propping this up on our Heroku instance!

Thanks @maxhm10 for bringing this issue up & @snajmi for helping get this live again.

**Comment by ryankanno** [comment]
I know I'm really late to this discussion, but I'm a local developer who's recently moved back home to Hawaii. I'm planning to help @bytemarks revive the local CfA brigades through http://hicapacity.org. This looks pretty amazing; who should I get into touch with to see how I can get some of this data and would absolutely love to bounce some ideas to get some of this momentum back for Honolulu.

**Comment by ryankanno** [comment]
Just circling back - sorry I'm so annoying - but wondering who I should contact to see if I can get a dump of this data? :)

**Comment by StraubCreative** [comment]
Ryan, I reached out to Catherine Bracy of CfA on Twitter and she pointed me
in a good direction. Last time I spoke to her they were working on a more
stable version - and that was about a year ago.

On Tue, Apr 14, 2015 at 6:13 PM, Ryan Kanno <notifications@github.com>
wrote:

> Just circling back - sorry I'm so annoying - but wondering who I should
> contact to see if I can get a dump of this data? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/honolulu_answers/issues/61#issuecomment-93131536>
> .
>



-- 

*Straub Creative Company*


*Zachary Straub *| Founder / Owner

*Let’s Build Better Things Together*

a: 100 Ellwood Avenue, Buffalo, NY 14223

p: (716) 301-0973 | e: zac@straubcreative.com

w: http://straubcreative.nationbuilder.com

<https://www.facebook.com/straubcreativecompany>
<https://twitter.com/straubcreative>
<https://plus.google.com/+StraubCreativeCompanyBuffalo/>
<https://www.linkedin.com/profile/view?id=118012357&trk=nav_responsive_tab_profile>
   <http://www.pinterest.com/straubcreative/>
<http://www.yelp.com/biz/straub-creative-company-buffalo>
<https://foursquare.com/v/straub-creative-company/543867d6498e0160f9de7d99>

**Comment by snajmi** [comment]
Hi all,

I have a dump of the data, as does Joey Cody, who was working on getting up an instance of Honolulu Answers. I'm traveling right now, but send me an email and I can fill you in.

On Apr 14, 2015, at 6:18 PM, Zachary Straub <notifications@github.com> wrote:

Ryan, I reached out to Catherine Bracy of CfA on Twitter and she pointed me
in a good direction. Last time I spoke to her they were working on a more
stable version - and that was about a year ago.

On Tue, Apr 14, 2015 at 6:13 PM, Ryan Kanno <notifications@github.com>
wrote:

> Just circling back - sorry I'm so annoying - but wondering who I should
> contact to see if I can get a dump of this data? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/honolulu_answers/issues/61#issuecomment-93131536>
> .
>



-- 

*Straub Creative Company*


*Zachary Straub *| Founder / Owner

*Let’s Build Better Things Together*

a: 100 Ellwood Avenue, Buffalo, NY 14223

p: (716) 301-0973 | e: zac@straubcreative.com

w: http://straubcreative.nationbuilder.com

<https://www.facebook.com/straubcreativecompany>
<https://twitter.com/straubcreative>
<https://plus.google.com/+StraubCreativeCompanyBuffalo/>
<https://www.linkedin.com/profile/view?id=118012357&trk=nav_responsive_tab_profile>
<http://www.pinterest.com/straubcreative/>
<http://www.yelp.com/biz/straub-creative-company-buffalo>
<https://foursquare.com/v/straub-creative-company/543867d6498e0160f9de7d99>

**Comment by snajmi** [comment]
Ryan, my email address is sheba@codeforamerica.org
ᐧ

**Comment by snajmi** [comment]
It's up at hnlanswers.herokuapp.com
