### ISSUE TITLE
"Contribute" link in footer points to the wrong GitHub repo URL

### ISSUE THREAD

**Issue by snajmi** [codeforamerica/honolulu_answers#63]
The "Contribute" link in the footer of Honolulu Answers points to the wrong GitHub repo. It points to https://github.com/honolulu/honolulu_answers but should point to https://github.com/codeforamerica/honolulu_answers

**Comment by rbvea** [comment]
@snajmi, thanks! that should be fixed now: http://hnlanswers.herokuapp.com
